"""initial_schema

Revision ID: 9f536c54833a
Revises:
Create Date: 2026-02-05 23:09:16.235962
"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f536c54833a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("github_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("access_token", sa.String(length=255), nullable=True),
        sa.Column("total_stars", sa.Integer(), nullable=False),
        sa.Column("synced_stars", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "clusters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("keywords", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("repo_count", sa.Integer(), nullable=False),
        sa.Column(
            "center_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024),
            nullable=True,
        ),
        sa.Column("center_x", sa.Float(), nullable=True),
        sa.Column("center_y", sa.Float(), nullable=True),
        sa.Column("center_z", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_clusters_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clusters")),
    )
    op.create_index(op.f("ix_clusters_user_id"), "clusters", ["user_id"], unique=False)
    op.create_table(
        "star_lists",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("github_list_id", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("repo_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_star_lists_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_star_lists")),
    )
    op.create_index(
        op.f("ix_star_lists_github_list_id"),
        "star_lists",
        ["github_list_id"],
        unique=False,
    )
    op.create_index(
        "ix_star_lists_user_github",
        "star_lists",
        ["user_id", "github_list_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_star_lists_user_id"), "star_lists", ["user_id"], unique=False
    )
    op.create_table(
        "sync_schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule_hour", sa.Integer(), nullable=False),
        sa.Column("schedule_minute", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_status", sa.String(length=20), nullable=True),
        sa.Column("last_run_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sync_schedules_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_schedules")),
    )
    op.create_index(
        op.f("ix_sync_schedules_user_id"), "sync_schedules", ["user_id"], unique=True
    )
    op.create_table(
        "sync_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("processed_items", sa.Integer(), nullable=False),
        sa.Column("failed_items", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "error_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sync_tasks_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_tasks")),
    )
    op.create_index(
        op.f("ix_sync_tasks_status"), "sync_tasks", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_sync_tasks_user_id"), "sync_tasks", ["user_id"], unique=False
    )
    op.create_table(
        "starred_repos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("github_repo_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=100), nullable=True),
        sa.Column("topics", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("homepage_url", sa.String(length=500), nullable=True),
        sa.Column("html_url", sa.String(length=500), nullable=False),
        sa.Column("owner_avatar_url", sa.String(length=500), nullable=True),
        sa.Column("stargazers_count", sa.Integer(), nullable=False),
        sa.Column("forks_count", sa.Integer(), nullable=False),
        sa.Column("watchers_count", sa.Integer(), nullable=False),
        sa.Column("open_issues_count", sa.Integer(), nullable=False),
        sa.Column("readme_content", sa.Text(), nullable=True),
        sa.Column("embedding_text", sa.Text(), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True
        ),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("ai_tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("star_list_id", sa.Integer(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("coord_x", sa.Float(), nullable=True),
        sa.Column("coord_y", sa.Float(), nullable=True),
        sa.Column("coord_z", sa.Float(), nullable=True),
        sa.Column("starred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("repo_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("repo_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("repo_pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_readme_fetched", sa.Boolean(), nullable=False),
        sa.Column("is_embedded", sa.Boolean(), nullable=False),
        sa.Column("is_summarized", sa.Boolean(), nullable=False),
        sa.Column("description_hash", sa.String(length=32), nullable=True),
        sa.Column("topics_hash", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name=op.f("fk_starred_repos_cluster_id_clusters"),
        ),
        sa.ForeignKeyConstraint(
            ["star_list_id"],
            ["star_lists.id"],
            name=op.f("fk_starred_repos_star_list_id_star_lists"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_starred_repos_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_starred_repos")),
    )
    op.create_index(
        op.f("ix_starred_repos_cluster_id"),
        "starred_repos",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_starred_repos_github_repo_id"),
        "starred_repos",
        ["github_repo_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_starred_repos_is_embedded"),
        "starred_repos",
        ["is_embedded"],
        unique=False,
    )
    op.create_index(
        "ix_starred_repos_language",
        "starred_repos",
        ["user_id", "language"],
        unique=False,
    )
    op.create_index(
        op.f("ix_starred_repos_star_list_id"),
        "starred_repos",
        ["star_list_id"],
        unique=False,
    )
    op.create_index(
        "ix_starred_repos_starred_at",
        "starred_repos",
        ["user_id", "starred_at"],
        unique=False,
    )
    op.create_index(
        "ix_starred_repos_user_github",
        "starred_repos",
        ["user_id", "github_repo_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_starred_repos_user_id"), "starred_repos", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_starred_repos_user_id"), table_name="starred_repos")
    op.drop_index("ix_starred_repos_user_github", table_name="starred_repos")
    op.drop_index("ix_starred_repos_starred_at", table_name="starred_repos")
    op.drop_index(op.f("ix_starred_repos_star_list_id"), table_name="starred_repos")
    op.drop_index("ix_starred_repos_language", table_name="starred_repos")
    op.drop_index(op.f("ix_starred_repos_is_embedded"), table_name="starred_repos")
    op.drop_index(op.f("ix_starred_repos_github_repo_id"), table_name="starred_repos")
    op.drop_index(op.f("ix_starred_repos_cluster_id"), table_name="starred_repos")
    op.drop_table("starred_repos")
    op.drop_index(op.f("ix_sync_tasks_user_id"), table_name="sync_tasks")
    op.drop_index(op.f("ix_sync_tasks_status"), table_name="sync_tasks")
    op.drop_table("sync_tasks")
    op.drop_index(op.f("ix_sync_schedules_user_id"), table_name="sync_schedules")
    op.drop_table("sync_schedules")
    op.drop_index(op.f("ix_star_lists_user_id"), table_name="star_lists")
    op.drop_index("ix_star_lists_user_github", table_name="star_lists")
    op.drop_index(op.f("ix_star_lists_github_list_id"), table_name="star_lists")
    op.drop_table("star_lists")
    op.drop_index(op.f("ix_clusters_user_id"), table_name="clusters")
    op.drop_table("clusters")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
