"""initial_schema

Revision ID: 35527331a075
Revises:
Create Date: 2026-02-05 22:56:57.736875
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35527331a075"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule_hour", sa.Integer(), nullable=False),
        sa.Column("schedule_minute", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_status", sa.String(length=20), nullable=True),
        sa.Column("last_run_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sync_schedules_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_schedules")),
    )
    op.create_index(
        op.f("ix_sync_schedules_user_id"), "sync_schedules", ["user_id"], unique=True
    )
    op.add_column(
        "starred_repos",
        sa.Column("description_hash", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "starred_repos", sa.Column("topics_hash", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("starred_repos", "topics_hash")
    op.drop_column("starred_repos", "description_hash")
    op.drop_index(op.f("ix_sync_schedules_user_id"), table_name="sync_schedules")
    op.drop_table("sync_schedules")
    # ### end Alembic commands ###
