"""add_star_lists_avatar_tags

Revision ID: 04bee8b1629c
Revises:
Create Date: 2026-02-04 14:24:13.468543
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04bee8b1629c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "star_lists",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("github_list_id", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("repo_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_star_lists_github_list_id"),
        "star_lists",
        ["github_list_id"],
        unique=False,
    )
    op.create_index(
        "ix_star_lists_user_github",
        "star_lists",
        ["user_id", "github_list_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_star_lists_user_id"), "star_lists", ["user_id"], unique=False
    )
    op.add_column(
        "starred_repos",
        sa.Column("owner_avatar_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "starred_repos",
        sa.Column("ai_tags", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "starred_repos", sa.Column("star_list_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_starred_repos_star_list_id"),
        "starred_repos",
        ["star_list_id"],
        unique=False,
    )
    op.create_foreign_key(None, "starred_repos", "star_lists", ["star_list_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "starred_repos", type_="foreignkey")
    op.drop_index(op.f("ix_starred_repos_star_list_id"), table_name="starred_repos")
    op.drop_column("starred_repos", "star_list_id")
    op.drop_column("starred_repos", "ai_tags")
    op.drop_column("starred_repos", "owner_avatar_url")
    op.drop_index(op.f("ix_star_lists_user_id"), table_name="star_lists")
    op.drop_index("ix_star_lists_user_github", table_name="star_lists")
    op.drop_index(op.f("ix_star_lists_github_list_id"), table_name="star_lists")
    op.drop_table("star_lists")
    # ### end Alembic commands ###
